CREATE VIEW CHARACTERVIEW AS
SELECT CHARACTERS.FirstName, CHARACTERS.LastName, BACKGROUND.BackgroundName, CLASS.ClassName, RACE.RaceName, USERS.Username
FROM CHARACTERS
INNER JOIN BACKGROUND ON BACKGROUND.BackgroundID=CHARACTERS.BackgroundID
INNER JOIN CLASS ON CLASS.ClassID=CHARACTERS.ClassID
INNER JOIN RACE ON RACE.RaceID=CHARACTERS.RaceID
INNER JOIN USERS ON USERS.UserID=CHARACTERS.UserID;